Repository TeamHavit/Havit-Server, pull requests merged in 2022-11, with the labels that each got.

#276 [FIX] content push 생성 시 isSeen 필드 추가
  functions/api/routes/content/contentNotificationPATCH.js
  functions/api/routes/content/contentPOST.js
Labels: 🔧 fix, 🛠 refactor, 🥱 jobchae

#278 [FEAT] 릴리즈 서버 분리를 위한 설정
  .firebaserc
  .github/workflows/dev.yml
  .github/workflows/prod.yml
  .gitignore
  functions/api/routes/auth/reissueTokenPOST.js
  functions/api/routes/auth/signinPOST.js
  functions/api/routes/auth/signupPOST.js
  functions/api/routes/auth/userDELETE.js
  functions/api/routes/category/categoryContentGET.js
  functions/api/routes/category/categoryContentSearchGET.js
  functions/api/routes/category/categoryDELETE.js
  functions/api/routes/category/categoryGET.js
  functions/api/routes/category/categoryNameGET.js
  functions/api/routes/category/categoryOrderPATCH.js
  functions/api/routes/category/categoryPATCH.js
  functions/api/routes/category/categoryPOST.js
  functions/api/routes/content/contentCategoryGET.js
  functions/api/routes/content/contentCategoryPATCH.js
  functions/api/routes/content/contentCheckPATCH.js
  functions/api/routes/content/contentDELETE.js
  functions/api/routes/content/contentListGET.js
  functions/api/routes/content/contentNotificationDELETE.js
  functions/api/routes/content/contentNotificationGET.js
  functions/api/routes/content/contentNotificationPATCH.js
  functions/api/routes/content/contentPOST.js
  functions/api/routes/content/contentRecentListGET.js
  functions/api/routes/content/contentRenamePATCH.js
  functions/api/routes/content/contentSearchGET.js
  functions/api/routes/content/contentUnseenListGET.js
  functions/api/routes/notice/noticeGET.js
  functions/api/routes/recommendation/recommendationGET.js
  functions/api/routes/user/userGET.js
  functions/api/routes/user/userNicknamePATCH.js
  functions/api/routes/user/userUpdateFcmTokenPUT.js
  functions/index.js
  functions/lib/kakaoAuth.js
  functions/middlewares/auth.js
  functions/middlewares/slackAPI.js
Labels: 🚀 enhancement, 🤩 philip

#280 [CHORE] 콘텐츠, 카테고리 삭제 시 userId도 검증하도록 수정
  functions/api/routes/category/categoryDELETE.js
  functions/api/routes/content/contentDELETE.js
  functions/db/category.js
  functions/db/content.js
  functions/lib/kakaoAuth.js
Labels: 🔧 fix, 🤩 philip

#281 [FIX] prod 서버 push server url, dev 서버 node_env 수정
  .github/workflows/prod.yml
  functions/package.json
Labels: 🔧 fix, 🤩 philip

#279 [FEAT] 릴리즈 서버 분리를 위한 설정
  .firebaserc
  .github/workflows/dev.yml
  .github/workflows/prod.yml
  .gitignore
  functions/api/routes/auth/reissueTokenPOST.js
  functions/api/routes/auth/signinPOST.js
  functions/api/routes/auth/signupPOST.js
  functions/api/routes/auth/userDELETE.js
  functions/api/routes/category/categoryContentGET.js
  functions/api/routes/category/categoryContentSearchGET.js
  functions/api/routes/category/categoryDELETE.js
  functions/api/routes/category/categoryGET.js
  functions/api/routes/category/categoryNameGET.js
  functions/api/routes/category/categoryOrderPATCH.js
  functions/api/routes/category/categoryPATCH.js
  functions/api/routes/category/categoryPOST.js
  functions/api/routes/content/contentCategoryGET.js
  functions/api/routes/content/contentCategoryPATCH.js
  functions/api/routes/content/contentCheckPATCH.js
  functions/api/routes/content/contentDELETE.js
  functions/api/routes/content/contentListGET.js
  functions/api/routes/content/contentNotificationDELETE.js
  functions/api/routes/content/contentNotificationGET.js
  functions/api/routes/content/contentNotificationPATCH.js
  functions/api/routes/content/contentPOST.js
  functions/api/routes/content/contentRecentListGET.js
  functions/api/routes/content/contentRenamePATCH.js
  functions/api/routes/content/contentSearchGET.js
  functions/api/routes/content/contentUnseenListGET.js
  functions/api/routes/notice/noticeGET.js
  functions/api/routes/recommendation/recommendationGET.js
  functions/api/routes/user/userGET.js
  functions/api/routes/user/userNicknamePATCH.js
  functions/api/routes/user/userUpdateFcmTokenPUT.js
  functions/db/category.js
  functions/db/content.js
  functions/index.js
  functions/lib/kakaoAuth.js
  functions/middlewares/auth.js
  functions/middlewares/slackAPI.js
  functions/package.json
Labels: 🚀 enhancement, 🤩 philip

#284 [FIX] Github Actions 설정 파일에서 배포할 Firebase Project 명시적으로 지정
  .github/workflows/dev.yml
  .github/workflows/prod.yml
Labels: 🔧 fix, 🤩 philip

#286 [FIX] Github Actions 오류 수정
  .github/workflows/dev.yml
  .github/workflows/prod.yml
  functions/index.js
Labels: 🔧 fix, 🤩 philip

#287 [FIX] Github Actions yml 파일 수정
  .github/workflows/dev.yml
  .github/workflows/prod.yml
Labels: 🔧 fix, 🤩 philip

#288 [FEAT] Firebase Hosting과 Firebase Functions 연결
  .github/workflows/dev.yml
  .github/workflows/prod.yml
  firebase.json
  functions/package.json
Labels: 🚀 enhancement, 🤩 philip

#289 [FIX] prod.yml action-slack indent 수정
  .github/workflows/prod.yml
Labels: 🔧 fix, 🤩 philip

#290 [FIX] hosting 배포 script 수정
  functions/package.json
Labels: 🔧 fix, 🤩 philip

#291 [FIX] 모든 요청 functions로 보내도록 수정
  firebase.json
Labels: 🔧 fix, 🤩 philip

#292 [FIX] 중복된 dotenv.config 삭제
  functions/api/index.js
  functions/db/db.js
  functions/middlewares/slackAPI.js
Labels: 🔧 fix, 🤩 philip

#293 [FIX] Firebase Hosting에 region 명시
  firebase.json
Labels: 🔧 fix, 🤩 philip

#295 [FIX] NODE_ENV 설정 오류 수정
  .firebaserc
  functions/index.js
Labels: 🔧 fix, 🤩 philip

#296 [FIX] yml file의 firebase use 구문에 변경된 alias 적용
  .github/workflows/dev.yml
  .github/workflows/prod.yml
Labels: 🔧 fix, 🤩 philip

#297 [FIX] hosting의 모든 요청 functions로 전송
  firebase.json
Labels: 🔧 fix, 🤩 philip

#298 [HOTFIX] prod yml create-json 구문 오류 수정
  .github/workflows/prod.yml
Labels: 🔧 fix, 🤩 philip

#299 [HOTFIX] prod yml create-json 구문 오류 수정
  .github/workflows/prod.yml
Labels: 🔧 fix, 🤩 philip

#301 [FEAT] Upptime health check 연결
  functions/api/routes/health/healthCheckGET.js
  functions/api/routes/health/index.js
  functions/api/routes/index.js
  functions/constants/responseMessage.js
Labels: 🚀 enhancement, 🤩 philip

#302 [FEAT] Prod 서버 Upptime health check 연결
  functions/api/routes/health/healthCheckGET.js
  functions/api/routes/health/index.js
  functions/api/routes/index.js
  functions/constants/responseMessage.js
Labels: 🚀 enhancement, 🤩 philip
