Repository TeamHavit/Havit-Server, pull requests merged in 2022-01, with the labels that each got.

#3 [FEAT] jwt token 발급 검증 관련 코드 추가
  functions/.gitignore
  functions/constants/jwt.js
  functions/lib/jwtHandlers.js
  functions/middlewares/auth.js
  functions/package-lock.json
  functions/package.json
Labels: enhancement

#4 [FEAT] jwt token 핸들러, 발급 코드 추가
  functions/.gitignore
  functions/constants/jwt.js
  functions/lib/jwtHandlers.js
  functions/middlewares/auth.js
  functions/package-lock.json
  functions/package.json
Labels: enhancement

#6 [FEAT] slack webhook error monitoring 연결 코드 추가
  functions/middlewares/slackAPI.js
  functions/package-lock.json
  functions/package.json
Labels: enhancement

#11 [FEAT] POST /category 카테고리 생성 api
  functions/api/routes/category/categoryPOST.js
  functions/api/routes/category/index.js
  functions/api/routes/index.js
  functions/constants/responseMessage.js
  functions/db/category.js
  functions/db/index.js
  functions/middlewares/auth.js
Labels: enhancement

#44 [FEAT] GET /category/:categoryId?seen=&filter= 카테고리 별 콘텐츠 조회 api
  functions/api/routes/category/categoryContentGET.js
  functions/api/routes/category/index.js
  functions/constants/responseMessage.js
  functions/db/categoryContent.js
  functions/db/index.js
Labels: enhancement, priority 1️⃣

#46 [FEAT] GET /content 전체 콘텐츠 조회 api
  functions/api/routes/content/contentListGET.js
  functions/api/routes/content/index.js
  functions/constants/responseMessage.js
  functions/db/content.js
Labels: enhancement, priority 1️⃣

#51 [FEAT] PATCH /category/:categoryId 카테고리 수정 api 구현
  functions/api/routes/category/categoryPATCH.js
  functions/api/routes/category/index.js
  functions/constants/responseMessage.js
  functions/db/category.js
Labels: enhancement, priority 2️⃣

#54 [FEAT] GET /content/search/?keyword= 전체 콘텐츠 키워드 검색 api 구현
  functions/api/routes/content/contentSearchGET.js
  functions/api/routes/content/index.js
  functions/constants/responseMessage.js
  functions/db/content.js
Labels: enhancement, priority 2️⃣

#58 [FIX] 시간 기능 수정, 함수 주석 처리, loadsh 코드로 변환
  functions/api/routes/category/categoryContentGET.js
  functions/api/routes/category/categoryNameGET.js
  functions/api/routes/category/categoryPATCH.js
  functions/db/category.js
Labels: fix

#60 [FIX] 시간 데이터 처리, 코딩 컨벤션, 파일명 수정, 카테고리 내 콘텐츠 개수 카운트 로직 추가
  functions/api/routes/category/categoryContentGET.js
  functions/api/routes/category/categoryNameGET.js
  functions/api/routes/category/categoryPATCH.js
  functions/api/routes/content/contentCheckPATCH.js
  functions/api/routes/content/contentListGET.js
  functions/api/routes/content/contentPOST.js
  functions/api/routes/content/contentScrapGET.js
  functions/api/routes/content/contentSearchGET.js
  functions/api/routes/content/index.js
  functions/db/category.js
  functions/db/categoryContent.js
Labels: enhancement, fix

#61 [FIX] 시간 데이터 처리, 코딩 컨벤션, 파일명 수정, 카테고리 내 콘텐츠 개수 카운트 로직 추가
  functions/api/routes/content/contentCheckPATCH.js
  functions/api/routes/content/contentListGET.js
  functions/api/routes/content/contentPOST.js
  functions/api/routes/content/contentScrapGET.js
  functions/api/routes/content/contentSearchGET.js
  functions/api/routes/content/index.js
  functions/db/category.js
  functions/db/categoryContent.js
Labels: enhancement, fix

#64 [FEAT] DELETE /category/:categoryId 카테고리 삭제 api
  functions/api/routes/category/categoryDELETE.js
  functions/api/routes/category/index.js
  functions/constants/responseMessage.js
  functions/db/category.js
  functions/db/categoryContent.js
  functions/db/content.js
Labels: enhancement, priority 2️⃣

#69 [FIX] DB import 코딩 컨벤션 수정
  functions/api/routes/content/contentCheckPATCH.js
  functions/api/routes/content/contentListGET.js
  functions/api/routes/content/contentRecentListGET.js
  functions/api/routes/content/contentSearchGET.js
Labels: fix

#72 [FEAT] GET /content/unseen 봐야 하는 콘텐츠 조회 api
  functions/api/routes/content/contentUnseenListGET.js
  functions/api/routes/content/index.js
  functions/constants/responseMessage.js
  functions/db/content.js
Labels: enhancement, priority 2️⃣

#76 [FEAT] PATCH /content/:contentId 콘텐츠 제목 변경 api
  functions/api/routes/content/contentRenamePATCH.js
  functions/api/routes/content/index.js
  functions/constants/responseMessage.js
  functions/db/content.js
Labels: enhancement, priority 2️⃣

#78 [FEAT] DELETE /content/:contentId 콘텐츠 삭제 api
  functions/api/routes/category/categoryDELETE.js
  functions/api/routes/content/contentDELETE.js
  functions/api/routes/content/index.js
  functions/constants/responseMessage.js
  functions/db/categoryContent.js
  functions/db/content.js
  functions/db/notification.js
Labels: enhancement, priority 2️⃣

#81 [FEAT] PATCH /content/category 콘텐츠 카테고리 변경 api
  functions/api/routes/content/contentCategoryPATCH.js
  functions/api/routes/content/index.js
  functions/constants/responseMessage.js
Labels: enhancement, priority 3️⃣

#85 [FIX} 전체 API 점검 및 수정
  functions/api/routes/content/contentCheckPATCH.js
  functions/api/routes/content/contentDELETE.js
  functions/api/routes/content/contentListGET.js
  functions/api/routes/content/contentPOST.js
  functions/api/routes/content/contentRecentListGET.js
  functions/api/routes/content/contentRenamePATCH.js
  functions/api/routes/content/contentScrapGET.js
  functions/api/routes/content/contentSearchGET.js
  functions/api/routes/content/contentUnseenListGET.js
  functions/db/category.js
  functions/db/content.js
  functions/db/index.js
  functions/db/notification.js
Labels: fix

#88 [FIX] category 라우트 API 로직, responseMessage, statusCode 수정
  functions/api/routes/category/categoryContentGET.js
  functions/api/routes/category/categoryDELETE.js
  functions/api/routes/content/contentCheckPATCH.js
  functions/db/categoryContent.js
Labels: enhancement, fix

#91 [FEAT] 콘텐츠 생성, 콘텐츠 카테고리 수정 API 유저 검증 로직 추가, 생성 API statusCode 201로 수정
  functions/api/routes/category/categoryPOST.js
  functions/api/routes/content/contentCategoryPATCH.js
  functions/api/routes/content/contentPOST.js
  functions/db/category.js
Labels: enhancement

#95 [FIX] order_index 0으로 들어가는 문제 수정
  functions/api/routes/category/categoryPOST.js
Labels: fix

#97 [FEAT] PATCH /content/notification 콘텐츠 알림 시각 변경 api
  functions/api/routes/content/contentCategoryPATCH.js
  functions/api/routes/content/contentNotificationPATCH.js
  functions/api/routes/content/index.js
  functions/constants/responseMessage.js
  functions/db/content.js
Labels: enhancement

#101 [FEAT] PATCH /category/order 카테고리 순서 변경 api
  functions/api/routes/category/categoryOrderPATCH.js
  functions/api/routes/category/index.js
  functions/constants/responseMessage.js
  functions/db/category.js
Labels: enhancement, priority 3️⃣

#104 [FIX] 카테고리 전체 조회 response imageId 추가
  functions/db/category.js
Labels: fix

#107 [FEAT] 카테고리 별 콘텐츠 조회 API isNotified 기준 추가, notification 테이블 연결 로직 삭제
  functions/api/routes/category/categoryContentGET.js
  functions/db/categoryContent.js
Labels: enhancement, fix

#114 [FIX] POST /content response data에 contentId 추가
  functions/api/routes/content/contentPOST.js
Labels: fix

#116 [FIX] 카테고리 별 콘텐츠 조회 API 오류 수정
  functions/api/routes/category/categoryContentGET.js
Labels: fix

#118 [FIX] statusCode 확인 및 수정, contentPOST API notificationTime 빈 값으로 받도록 수정, contentCheckPATCH DB 예외 처리 추가
  functions/api/routes/category/categoryOrderPATCH.js
  functions/api/routes/content/contentCheckPATCH.js
  functions/api/routes/content/contentDELETE.js
  functions/api/routes/content/contentNotificationPATCH.js
  functions/api/routes/content/contentPOST.js
  functions/api/routes/content/contentRenamePATCH.js
  functions/db/content.js
Labels: fix

#119 [FIX] statusCode 확인 및 수정, contentPOST API notificationTime 빈 값으로 받도록 수정, contentCheckPATCH DB 예외 처리 추가
  functions/api/routes/category/categoryOrderPATCH.js
  functions/api/routes/content/contentCheckPATCH.js
  functions/api/routes/content/contentDELETE.js
  functions/api/routes/content/contentNotificationPATCH.js
  functions/api/routes/content/contentPOST.js
  functions/api/routes/content/contentRenamePATCH.js
  functions/db/content.js
Labels: fix

#121 [FEAT] 카테고리 전체 조회 API 카테고리 별 콘텐츠 수 조회 로직 추가
  .github/workflows/main.yml
  README.md
  functions/api/routes/category/categoryGET.js
Labels: enhancement

#122 [FEAT] 카테고리 전체 조회 API 카테고리 별 콘텐츠 수 조회 로직 추가
  functions/api/routes/category/categoryGET.js
Labels: enhancement

#125 [FEAT] GET /user 유저 정보 API
  functions/api/routes/index.js
  functions/api/routes/user/index.js
  functions/api/routes/user/userGET.js
  functions/db/index.js
  functions/db/user.js
Labels: enhancement, priority 2️⃣

#129 [FIX] 콘텐츠 알림 시각 변경 API 알림 Off->On 변경 시 로직 수정
  functions/db/content.js
Labels: fix

#132 [FEAT] 콘텐츠 전체 조회 API filter, option 추가
  functions/api/routes/content/contentListGET.js
  functions/db/content.js
Labels: enhancement

#135 [FEAT] Firebase Deploy 자동화, Deploy Message Slack 전송 로직 추가, 유저 정보 조회 API 콘텐츠 개수 카운트 로직 수정
  .gitignore
  firebase.json
  functions/api/routes/user/userGET.js
Labels: enhancement, fix

#139 [FIX] 콘텐츠 스크랩 API response ogImage string 타입으로 수정
  functions/api/routes/content/contentScrapGET.js
Labels: fix
