Repository TeamHavit/Havit-Server, pull requests merged in 2022-08, with the labels that each got.

#228 [REFACTOR] fcm token update axios 로직 push handler 로 이전
  functions/api/routes/user/userUpdateFcmTokenPUT.js
  functions/lib/pushServerHandlers.js
Labels: 🛠 refactor, 🥱 jobchae

#232 [FIX] og tag 스크래핑 시 image url property 가 없는 경우 처리
  functions/api/routes/content/contentPOST.js
Labels: bug, 🥱 jobchae

#241 [FIX] 콘텐츠 조회 알림 필터링 시 알림 예정만 가져오도록 수정
  functions/db/categoryContent.js
  functions/db/content.js
Labels: 🔧 fix, 🥱 jobchae

#242 [FEAT] 기존 유저 로그인 시 fcm 토큰 업데이트
  functions/api/routes/auth/signinPOST.js
Labels: 🚀 enhancement, 🔧 fix, 🥱 jobchae

#238 [FEAT] 콘텐츠 알림 삭제 API 구현, 푸시 서버 연동
  functions/api/routes/content/contentNotificationDELETE.js
  functions/api/routes/content/contentNotificationPATCH.js
  functions/api/routes/content/index.js
  functions/constants/responseMessage.js
  functions/db/content.js
  functions/lib/pushServerHandlers.js
Labels: 🚀 enhancement, 🥱 jobchae

#246 [FIX] 콘텐츠 생성 API 크롤링 로직 삭제
  functions/api/routes/content/contentPOST.js
Labels: 🔧 fix, 🤩 philip

#250 [FIX] 콘텐츠 알림 시간 변경 시 이미 지난 알림 다시 생성하도록 분기 처리
  functions/api/routes/content/contentNotificationPATCH.js
Labels: 🔧 fix, 🥱 jobchae
