Repository TeamHavit/Havit-Server, pull requests merged in 2022-07, with the labels that each got.

#215 [FIX] 카테고리, 콘텐츠 생성 API 중복 방지 로직 삭제
  functions/api/routes/category/categoryPOST.js
  functions/api/routes/content/contentPOST.js
Labels: fix

#218 [FEAT] 회원 탈퇴 API User UID string concat 처리
  functions/api/routes/auth/userDELETE.js
  functions/db/user.js
  functions/package-lock.json
  functions/package.json
Labels: enhancement

#225 [FIX] 푸시 알림 수정 - 푸시 서버 통신 구현
  functions/api/routes/content/contentNotificationPATCH.js
  functions/api/routes/content/index.js
  functions/constants/responseMessage.js
  functions/db/content.js
  functions/lib/pushServerHandlers.js
Labels: 🚀 enhancement, 🥱 jobchae
