Repository TeamHavit/Havit-Server, pull requests merged in 2022-09, with the labels that each got.

#253 [FEAT] 회원 가입 시 선택약관 동의 여부 수집
  functions/api/routes/auth/signupPOST.js
  functions/db/user.js
Labels: 🚀 enhancement, 🤩 philip

#256 [FIX] 콘텐츠 타이틀 변경 시 푸시 서버에 반영하기
  functions/api/routes/content/contentRenamePATCH.js
  functions/lib/pushServerHandlers.js
Labels: 🔧 fix, 🥱 jobchae

#257 [FIX] 회원가입 시 리프레시 토큰 저장되지 않는 오류 수정
  .github/workflows/main.yml
  functions/api/routes/auth/signupPOST.js
  functions/api/routes/content/contentRenamePATCH.js
  functions/db/user.js
  functions/lib/pushServerHandlers.js
Labels: 🔧 fix, 🤩 philip

#258 [FIX] 회원가입 시 리프레시 토큰 저장되지 않는 오류 수정
  functions/api/routes/auth/signupPOST.js
  functions/db/user.js
Labels: 🔧 fix, 🤩 philip

#260 [FEAT] 최근 저장 콘텐츠 조회 API 소속 카테고리 이름 추가
  functions/api/routes/content/contentRecentListGET.js
Labels: 🚀 enhancement, 🤩 philip

#262 [FEAT] 공지사항 조회 기능 추가
  functions/api/routes/index.js
  functions/api/routes/notice/index.js
  functions/api/routes/notice/noticeGET.js
  functions/constants/responseMessage.js
  functions/db/index.js
  functions/db/notice.js
Labels: 🚀 enhancement, 🤩 philip

#264 [CHORE] notice 라우트 checkUser 삭제
  functions/api/routes/notice/index.js
Labels: 🔧 fix, 🤩 philip

#263 [FEAT] 공지사항 조회 기능 추가
  functions/api/routes/index.js
  functions/api/routes/notice/index.js
  functions/api/routes/notice/noticeGET.js
  functions/constants/responseMessage.js
  functions/db/index.js
  functions/db/notice.js
Labels: 🚀 enhancement, 🤩 philip

#266 [CHORE] dayjs로 createdAt format 변환
  functions/api/routes/notice/noticeGET.js
Labels: 🔧 fix, 🤩 philip

#268 [CHORE] 공지사항 dayjs 포맷팅 Promise.all 처리
  functions/api/routes/notice/noticeGET.js
Labels: 🚀 enhancement, 🤩 philip

#270 [CHORE] 불필요한 await 삭제
  functions/api/routes/notice/noticeGET.js
Labels: 🔧 fix, 🤩 philip

#271 [CHORE] 불필요한 async 제거
  functions/api/routes/notice/noticeGET.js
Labels: 🔧 fix, 🤩 philip

#267 [CHORE] dayjs로 createdAt format 변환
  functions/api/routes/notice/noticeGET.js
Labels: 🔧 fix, 🤩 philip

#272 [FIX] dayjs format 변환 로직 비동기 처리
  functions/api/routes/category/categoryContentGET.js
  functions/api/routes/category/categoryContentSearchGET.js
  functions/api/routes/content/contentCategoryGET.js
  functions/api/routes/content/contentListGET.js
  functions/api/routes/content/contentNotificationGET.js
  functions/api/routes/content/contentRecentListGET.js
  functions/api/routes/content/contentSearchGET.js
  functions/api/routes/content/contentUnseenListGET.js
  functions/api/routes/notice/noticeGET.js
  functions/db/content.js
Labels: 🔧 fix, 🤩 philip

#273 [FIX] dayjs format 변환 로직 비동기 처리
  functions/api/routes/category/categoryContentGET.js
  functions/api/routes/category/categoryContentSearchGET.js
  functions/api/routes/content/contentCategoryGET.js
  functions/api/routes/content/contentListGET.js
  functions/api/routes/content/contentNotificationGET.js
  functions/api/routes/content/contentRecentListGET.js
  functions/api/routes/content/contentSearchGET.js
  functions/api/routes/content/contentUnseenListGET.js
  functions/api/routes/notice/noticeGET.js
  functions/db/content.js
Labels: 🔧 fix, 🤩 philip
