Repository TeamHavit/Havit-Server, pull requests merged in 2024-03, with the labels that each got.

#327 [FEAT] swagger setup
  .github/workflows/dev.yml
  .gitignore
  functions/api/index.js
  functions/api/routes/index.js
  functions/api/routes/notice/index.js
  functions/config/swagger.js
  functions/constants/swagger/schemas/commonErrorSchema.js
  functions/constants/swagger/schemas/index.js
  functions/constants/swagger/schemas/noticeSchema.js
  functions/package-lock.json
  functions/package.json
Labels: 🚀 enhancement, setting ⚙️, 🥱 jobchae

#330 [FIX] swagger-ui package 종속성 문제 해결
  .github/workflows/dev.yml
  functions/package-lock.json
  functions/package.json
Labels: 🔧 fix, setting ⚙️, 🥱 jobchae

#331 [FEAT] 커뮤니티 카테고리, 게시글 상세 조회 swagger 명세
  .gitignore
  functions/api/index.js
  functions/api/routes/community/communityCategoryGET.js
  functions/api/routes/community/communityPostGET.js
  functions/api/routes/community/index.js
  functions/api/routes/index.js
  functions/config/swagger.js
  functions/constants/swagger/schemas/communitySchema.js
  functions/constants/swagger/schemas/index.js
Labels: 🚀 enhancement, 🥱 jobchae

#333 [FEAT] 게시글 전체 조회, 신고하기 swagger 명세
  functions/.pretterrc.js
  functions/.prettierrc.js
  functions/api/routes/community/communityCategoryPostsGET.js
  functions/api/routes/community/communityPostsGET.js
  functions/api/routes/community/communityReportPOST.js
  functions/api/routes/community/index.js
  functions/constants/swagger/schemas/communitySchema.js
Labels: 🚀 enhancement, 🤓 yubin

#335 [FEAT] community 게시글 작성 swagger 명세
  functions/api/routes/community/communityPostPOST.js
  functions/api/routes/community/index.js
  functions/constants/swagger/schemas/communitySchema.js
Labels: 🚀 enhancement, 🥱 jobchae

#339 [FEAT] 커뮤니티 게시글 상세조회 API
  functions/api/routes/community/communityPostGET.js
  functions/constants/dummyImages.js
  functions/constants/responseMessage.js
  functions/constants/swagger/schemas/communitySchema.js
  functions/db/community.js
  functions/db/index.js
Labels: 🚀 enhancement, 🥱 jobchae

#340 [BUGFIX] /community 산하 엔드포인트 리소스명 복수형으로 변경
  .github/ISSUE_TEMPLATE/-bugfix-.md
  functions/api/routes/community/communityCategoriesGET.js
  functions/api/routes/community/communityCategoryPostsGET.js
  functions/api/routes/community/communityReportPOST.js
  functions/api/routes/community/index.js
Labels: 🤩 hyositive
