Repository TeamHavit/Havit-Server, pull requests merged in 2024-04, with the labels that each got.

#346 [FEAT] 커뮤니티 카테고리 전체 조회 API
  functions/api/routes/auth/reissueTokenPOST.js
  functions/api/routes/community/communityCategoriesGET.js
  functions/constants/responseMessage.js
  functions/db/community.js
Labels: 🚀 enhancement, 🤩 hyositive

#347 [FEAT] 커뮤니티 게시글 작성 API
  functions/.prettierrc.js
  functions/api/routes/community/communityPostPOST.js
  functions/api/routes/community/index.js
  functions/constants/responseMessage.js
  functions/db/community.js
  functions/middlewares/validation.js
  functions/middlewares/validator/communityValidator.js
  functions/middlewares/validator/index.js
  functions/package-lock.json
  functions/package.json
Labels: 🚀 enhancement, 🥱 jobchae

#345 [FEAT] 커뮤니티 게시글 전체조회 API
  functions/api/routes/community/communityPostsGET.js
  functions/api/routes/community/index.js
  functions/config/swagger.js
  functions/constants/responseMessage.js
  functions/constants/swagger/schemas/communitySchema.js
  functions/db/community.js
  functions/middlewares/validator/communityValidator.js
Labels: 🚀 enhancement, 🤓 yubin

#348 [FEAT] 카테고리별 커뮤니티 게시글 조회 API
  functions/api/routes/community/communityCategoryPostsGET.js
  functions/api/routes/community/communityPostsGET.js
  functions/api/routes/community/index.js
  functions/constants/responseMessage.js
  functions/db/community.js
  functions/middlewares/validator/communityValidator.js
Labels: 🚀 enhancement, 🤓 yubin

#349 [FEAT] 커뮤니티 게시글 신고하기 API
  functions/api/routes/community/communityReportPOST.js
  functions/api/routes/community/index.js
  functions/constants/responseMessage.js
  functions/db/community.js
  functions/middlewares/validator/communityValidator.js
Labels: 🚀 enhancement, 🤩 hyositive

#351 [FIX] 커뮤니티 게시글 상세 조회 시 신고한 게시글 필터링 로직 추가
  functions/api/routes/community/communityPostGET.js
  functions/api/routes/community/index.js
  functions/constants/responseMessage.js
  functions/db/community.js
  functions/middlewares/validator/communityValidator.js
Labels: 🔧 fix, 🥱 jobchae
