Repository TeamHavit/Havit-Server, pull requests merged in 2024-06, with the labels that each got.

#356 [FEAT] 커뮤니티 게시물 삭제 API
  functions/api/routes/community/communityPostDELETE.js
  functions/api/routes/community/index.js
  functions/constants/responseMessage.js
  functions/constants/swagger/schemas/communitySchema.js
  functions/db/community.js
  functions/middlewares/validator/communityValidator.js
Labels: 🚀 enhancement, 🤓 yubin

#360 [FIX] 커뮤니티 게시물 카테고리별 조회 response에 게시물 작성자 본인여부 bool 타입 추가
  functions/db/community.js
Labels: 🔧 fix, 🤓 yubin

#361 [FEAT] 커뮤니티 게시글 신고 시 슬랙 알림 발송
  functions/api/routes/community/communityReportPOST.js
  functions/db/community.js
  functions/lib/slackMessage.js
  functions/middlewares/slackAPI.js
Labels: 🚀 enhancement, 🥱 jobchae
